/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    StreamingTutorEscrow: {
      address: "0x04f46939ece9c849f9230282b5887beac96a25a7",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "activeSessionIds",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getAllTutors",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSession",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StreamingTutorEscrow.Session",
              components: [
                {
                  name: "student",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tutor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "ratePerSecond",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "startTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "stopTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxDuration",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "depositAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "earnedAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "claimedAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "refundedAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum StreamingTutorEscrow.SessionStatus",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTutor",
          inputs: [
            {
              name: "tutorAddress",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StreamingTutorEscrow.Tutor",
              components: [
                {
                  name: "wallet",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "bio",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "languages",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "ratePerSecond",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "totalEarned",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalClaimed",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTutorClaimable",
          inputs: [
            {
              name: "tutorAddress",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTutorCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextSessionId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "refundUnused",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerTutor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "seedTutor",
          inputs: [
            {
              name: "tutor",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sessions",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "student",
              type: "address",
              internalType: "address",
            },
            {
              name: "tutor",
              type: "address",
              internalType: "address",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "stopTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxDuration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "depositAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "earnedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "refundedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum StreamingTutorEscrow.SessionStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setTutorActive",
          inputs: [
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startSession",
          inputs: [
            {
              name: "tutorAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "maxDuration",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stopSession",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "studentBalances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tutorList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tutors",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "totalEarned",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalClaimed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updateTutor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawBalance",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BalanceWithdrawn",
          inputs: [
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newBalance",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newBalance",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Refunded",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SessionStarted",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxDuration",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "depositAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SessionStopped",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "elapsedSeconds",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "earnedAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "refundableAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TutorRegistered",
          inputs: [
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TutorUpdated",
          inputs: [
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 27307703,
    },
  },
  31337: {
    StreamingTutorEscrow: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "activeSessionIds",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claim",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getAllTutors",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSession",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StreamingTutorEscrow.Session",
              components: [
                {
                  name: "student",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tutor",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "ratePerSecond",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "startTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "stopTime",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "maxDuration",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "depositAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "earnedAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "claimedAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "refundedAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum StreamingTutorEscrow.SessionStatus",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTutor",
          inputs: [
            {
              name: "tutorAddress",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct StreamingTutorEscrow.Tutor",
              components: [
                {
                  name: "wallet",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "name",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "bio",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "languages",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "ratePerSecond",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "active",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "totalEarned",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "totalClaimed",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTutorClaimable",
          inputs: [
            {
              name: "tutorAddress",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTutorCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nextSessionId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "refundUnused",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "registerTutor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "seedTutor",
          inputs: [
            {
              name: "tutor",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sessions",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "student",
              type: "address",
              internalType: "address",
            },
            {
              name: "tutor",
              type: "address",
              internalType: "address",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "startTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "stopTime",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "maxDuration",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "depositAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "earnedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "claimedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "refundedAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum StreamingTutorEscrow.SessionStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setTutorActive",
          inputs: [
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "startSession",
          inputs: [
            {
              name: "tutorAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "maxDuration",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "stopSession",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "studentBalances",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "tutorList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "tutors",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "totalEarned",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totalClaimed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updateTutor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "languages",
              type: "string",
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawBalance",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BalanceWithdrawn",
          inputs: [
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newBalance",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deposited",
          inputs: [
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newBalance",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Refunded",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SessionStarted",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxDuration",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "depositAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SessionStopped",
          inputs: [
            {
              name: "sessionId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "student",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "elapsedSeconds",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "earnedAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "refundableAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TutorRegistered",
          inputs: [
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TutorUpdated",
          inputs: [
            {
              name: "tutor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "name",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "ratePerSecond",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "active",
              type: "bool",
              indexed: false,
              internalType: "bool",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
